lgdd_site_homepage:
    pattern:  /
    defaults: { _controller: LGDDSiteBundle:Default:index }
lgdd_voir_article:
    pattern:  /article/{id}
    defaults: { _controller: LGDDSiteBundle:Default:voir }
