lgdd_Accueil:
    pattern:  /
    defaults: { _controller: LGDDSiteBundle:Default:voirAnnexe, annexeID: 1 }
lgdd_voir_annexe:
    pattern:  /annexe/{annexeID}
    defaults: { _controller: LGDDSiteBundle:Default:voirAnnexe, annexeID: 1 }
lgdd_voir_article:
    pattern:  /article/{id}
    defaults: { _controller: LGDDSiteBundle:Default:voirArticle }
