parameters:
#    lgdd_site.example.class: LGDD\SiteBundle\Example

services:
#    lgdd_site.example:
#        class: %lgdd_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
