<?php

namespace LGDD\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{

	
	public function getSousCategorie()
	{
	  $qb = $this->createQueryBuilder('c')
	             ->join('c.categorie', 'c2')
	             ->addSelect('c2');

	  return $qb->getQuery()
	            ->getResult();
	}

	public function getFirstLevel(){
		$qb = $this->createQueryBuilder('c')
				   ->where('c.parent IS NULL');

	  	return $qb->getQuery()
	              ->getResult();
	}
	
}
